CMakeLists.txt

Fixed an issue with new behaviour in cmake 3.0.0 according to this policy:
> Target names reserved by one or more CMake generators are not allowed.
> Among others these include "all", "help" and "test".
> The OLD behavior for this policy is to allow creating targets with
> reserved names or which do not match the validity pattern.
> The NEW behavior for this policy is to report an error
> if an add_* command is used with an invalid target name.
> This policy was introduced in CMake version 3.0.  CMake version
> 3.0.0 warns when the policy is not set and uses OLD behavior.  Use
> the cmake_policy command to set it to OLD or NEW explicitly.

Fixed cmake warning that targets shouldn't be named test.

---

tiny_obj_loader.cc

function parseString seemed to not increment token after it used strspn to get the length of the whitespace characters at the beginning of token. So strcspn called right after that would return 0 and the created string would be an empty string.
Seems to have been working so far since it gets passed strings that don't begin with whitespace characters.

Fix parseString ? and slight change to fixIndex

---

tiny_obj_loader.cc

This extremely minor change allows tinyobjloader to handle OBJ files that reference multiple MTL files. I'm not sure if this is a very common thing to encounter but Wikipedia says it's legal to have multiple mtllibs and it's such a small tweak I thought I'd see if you thought it was worth supporting.

Add support for referencing multiple mtllibs

---

CMakeLists.txt

Add CMake options to toggle the TestLoader application and OBJ Sticher application so that including the project has a smaller footprint

Add CMake options

---

tiny_obj_loader.cc

Fixes compile error on MSVC 10:
error C2668: 'pow' : ambiguous call to overloaded function

Changed pow function to use double overload

---

tiny_obj_loader.cc

If you have several groups with a `usemtl` line preceding the group definition `g`, all such groups except the last one are ignored. This should fix it.
I think this doesn't introduce side-effects, but it'd be good to test by loading some sample .obj files.
Problematic example file shared privately by email.

Fix groups being ignored if they have 'usemtl' just before 'g'

---

tiny_obj_loader.cc

Uses of `sscanf_s` give the following warnings in 64-bit builds:
tiny_obj_loader.cc(471): warning C4477: 'sscanf_s' : format string '%s' requires an argument of type 'int', but variadic argument 2 has type 'unsigned __int64'
tiny_obj_loader.cc(471): note: this argument is used as a buffer size
This was fixed by casting the uses of _countof(namebuf) to `unsigned`, since the MSDN documentation for `sscanf_s` specifies that "The size parameter is of type **unsigned**, not **size_t**." (https://msdn.microsoft.com/en-us/library/t6z7bya3.aspx) This fix silences the warnings.

fix sscanf_s buffer size type

---

tiny_obj_loader.h

Without this, MSVC complains about sscanf being unsafe.

use sscanf_s in MSVC

---

tiny_obj_loader.h

I have fixed an error with no triangulation + normal calculation.
I removed warnings.
Brace style changed.
Here there is a capture of head(http://graphics.cs.williams.edu/data/meshes.xml) with flat normals generated.
I hope that soon I can have the smooth normals.

Fixing errors normal generation no triangulation. Remove warnings. Coding Style.

---

tiny_obj_loader.h

1. Move heap-based objects like vectors and strings outside the parse loop in LoadObjWithCallback().
- This avoids reallocation on every use making the code faster.
2. 	Fix a crash _bug_ in `LoadObjWithCallback()` when passing a `nullptr` as `MaterialReader *readMatFn`. 
- This preserves the existing API. If `nullptr` is passed then the material file will be ignored. This is useful when the user is not interested in the materials but only in the geometry.
- Note that if `nullptr` is _not_ a valid option for this function, then the API needs to be changed to take `MaterialReader&`.

Crash bug fix + optimizations in LoadObjWithCallback()

---

tiny_obj_loader.h

Changes the `LoadObjWithCallback()` API to accept `std::istream&` instead of pointer since this is a _required_ argument.
Also changing the argument order to allow for defaults for _optional_ arguments.

Changes the LoadObjWithCallback() API

---

tiny_obj_loader.h

OBJ indices are 1 (or -1) based, so 0 is an invalid value.
This is an API breaking change.

Changes the value indicating non-existent index to 0. 

---

tiny_obj_loader.h

This PR has three improvements to the parser, one is avoiding reallocating the line buffer over and over again, one is to use a lookup table to avoid expensive calls to pow(), and the final one avoids the ldexp() and pow() calls for the case that the exponent is zero.
Parse times for some large .obj files (without asan):
```
File A  File B  File C
Before  2743ms   589ms   615ms
After   1037ms   203ms   190ms
```

Improve parsing speed by about a factor of 2 for large files

---

python/main.cpp

As of https://github.com/syoyo/tinyobjloader/commit/5eef2b0914316786ce820964495663d809c6bf88, vertex attributes appear to be inaccessible to Python; while `attribobj` is constructed to hold this data, this appears to be dead code, as no reference to `attribobj` is included in the return from `LoadObj`.
This patch simply adds the `attribobj` dictionary alongside `shapes` and `materials` in the returned object, with the name `attribs`.

(Re-)expose attributes to Python

---

python/TODO.md
python/main.cpp

This works for me; I'm not an expert on Python 2/3 compatibility but I don't believe any further changes are necessary.

Support Python 2.7

---

tiny_obj_loader.h

When I want use LoadObjWithCallback instead of LoadObj, I was getting error that material name not found. In body of this code I saw doubled line.

Fixed error in getting material name in LoadObjWithCallback

---

tiny_obj_loader.h

Currently tinyobjloader does not compile on QNX system, the reason is that cxxx headers are used instead of xxx.h. As it turns out, C++ standard does not guarantee that after inclusion of the cxxx header the functions it contain will be injected into global namespace [[1] see appendix D.5](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3690.pdf#appendix.D) [[2]](http://www.qnx.com/developers/docs/660/index.jsp?topic=%2Fcom.qnx.doc.dinkum%2Ftopic%2Fcpp11%2Findex.html) [[3]](https://developers.redhat.com/blog/2016/02/29/why-cstdlib-is-more-complicated-than-you-might-think/).
My change adds std:: before each call of the functions from cmath and sscanf. I have issues with only these ones. With this patch applied tinyobjloader compiles for me.
Maybe maintainers may think of making …

Add std namespace for pow, ldexp, sscanf function calls.

---

tiny_obj_loader.h

After processing one textureoption like "-s u v w" the next option " -o u v w" has a beginning whitespace. Due to this it does not match to the option "-o" and it is skipped.

Deal with more than one texture option

---

tiny_obj_loader.h

This pull request fixes a few [Cppcheck](http://cppcheck.sourceforge.net/) warnings.
* `Variable 'se' is assigned a value that is never used.`
* Fixed by calling `operator bool()` on the sentry instance before using it.
* `scanf without field width limits can crash with huge input data.`
* Fixed by replacing `sscanf` with ~~`std::snprintf`~~ `std::stringstream`
~~This also replaces a couple uses of `4096` with `TINYOBJ_SSCANF_BUFFER_SIZE` where it looks appropriate.~~ This deletes the macro `TINYOBJ_SSCANF_BUFFER_SIZE`. I've run `make check` and all tests pass.

Fix Cppcheck warnings

---

tiny_obj_loader.h

WE should remove the keyword `register' since it is no longer supported in C++17.

remove the keyword `register' for C++17

---

python/main.cpp

Material names can be retreived with `model["material_indicies"][IDX]`

[Python] Fix mapping for #131 and compilation error #139 #132 (related)

---

experimental/tinyobj_loader_opt.h

1. sometimes '\r' would appear in material file name which will lead to failure file finding
2. bugfix for obj file with multiple textures
-problem occurs when multiple texture material is defined in one obj, where material_id could not be read correctly. This is caused by 
(1) material_id is accessible among threads
(2) in one thread, material_id would stay -1 until a  use material command is encountered. 
So a check and fix for the material_id  is necessary after multithread merge

Bugfix for multiple texture

---

experimental/tinyobj_loader_opt.h

When a line started in a chunk, the algorithm only looked for its end in the following chunk, but the end of the line may actually be located even further. Instead, in this commit we look for the next new line until the end of the whole buffer.

Fix bug when line starts before a chunk and ends after it

---

examples/obj_sticher/obj_writer.cc
examples/obj_sticher/obj_writer.h

Changes:
- Changed signature (added attributes parameter) of WriteObj(...)
- Added the illum keyword to material file output
- Changed obj output style to the following format:
mtllib ...
[list-of-vertices]
[list-of-normals]
[list-of-texture-coords]
[groups-of-face-indices]
In this apporach I am assuming each shape/group either has vertex-normals (resp. texture-coords), or it doesn't, i.e. if one vertex has a normal, every other vertex within the same shape is assumed to have a normal as well.
Shifting the check for vertex normals (line 111) and texture-coords (line 112) into the per-face-loop (line 117) may be more precise, but also will reduce performance. Since I didn't see any example of faces within one group having different attributes yet, I left the check outside the loop.
To …

Adapt the v1.0.x data format to the WriteObj function

---

experimental/tinyobj_loader_opt.h

The OBJ loader was discarding the first line of a file
or a chunk following one that ends with a newline.
I found this bug when testing with a very small OBJ file and many (32) cores.

Fix bug that discarded some chunks.

---

tiny_obj_loader.h

Currently, if `mtl_basedir` doesn't end with a separator character (`/` on *nix or `\\` on Windows) the loader will neither raise any warning nor correctly load the materials. 
With this commit, `LoadObj` will automatically insert a separator at the end of the basedir if needed.

Ensure mtl_basedir ends with a directory separator

---

tiny_obj_loader.h

I needed to be able to import lines from an obj file I exported from blender and was disappointed to see it wasn't supported, so I added support; support for the 'l' character, similar to 'f' character. For more information check wikipedia: https://en.wikipedia.org/wiki/Wavefront_.obj_file#Line_elements
If there are any problems that I could fix than just say so. I hope this is of use to someone else. Thanks!

Added support for line paths.

---

tiny_obj_loader.h

A malformed obj file can have missing data but still have face indices.
This PR handles such a case by reporting an error and returning with a failed status.

Produce an error and return when indices and data dont match.

---

python/main.cpp

Dear all,
As described in the issue https://github.com/syoyo/tinyobjloader/issues/188#issue-385341218 there is a memory leak in the function pyLoadObj(). The reference count for all created Python objects must be decreased after they are fed into the lists and dictionaries. The only  exception from this is the function PyTuple_SetItem() in pyTupleFromfloat3(), which decreases the reference counter of the Python object *tuple automatically by calling this function. In all other cases like PyList_Insert(), the references are only borrowed and not decreased. Therefore, each created Python object will remain in the heap, since there is one reference to it left in the counter.
These facts are explained in https://docs.python.org/2/c-api/intro.html#reference-counts in detail.
Best regards …

 Fix of important memory leak in Python module

---

tiny_obj_loader.h

When loading large concave polygons (with triangulation enabled) I found that the resulting mesh was sometimes missing triangles. The issue seems to be the hard stop on 10 max iterations over the face vertices. 
The change introduced here relaxes that constraint but avoids an endless loop in case no progress is made after a complete iteration through all the vertices. It should be noted however that the time bound for the worst case after this change is higher than with the 10 iterations constraint. 
If you think this change is worth considering I can add a test case that doesn't pass with current implementation and is fixed by this change.

Change triangulation loop termination constraint

---

tiny_obj_loader.h

cppcheck complains about the `pad_` variable being uninitialized in the constructor:
~~~
[tiny_obj_loader.h:438]: (warning) Member variable 'face_t::pad_' is not initialized in the constructor.
~~~

tiny_obj_loader.h: initialize pad_ in constructor

---

CMakeLists.txt

Adding namespace for cmake export is becoming the standard, here are some reasons:
1. With namespace targets like Foo::Foo, if it's missing the config will give you an error rather than just silently adding -lFoo
2. The namespace is a nice way to tell when a library is imported vs part of the project, as most people do follow that standard for imported targets.
However, this is a non backwards compatible change, after this change, the way to link to tinyobjloader in cmake for the downstream will become
`target_link_libraries(${PROJECT_NAME} tinyobjloader::tinyobjloader)`

namespace for cmake export

---

experimental/tinyobj_loader_opt.h

The code was assuming the mtllib command to be near the beginning of the file, and therefore to always be read by the first thread.

Fix crash when reading mtllib command

---

CMakeLists.txt

CMake actually has an built-in variable [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) for a long time, so we should use it instead of defining a custom variable TINYOBJLOADER_COMPILATION_SHARED. 
The custom variable is causing inconvenience for CI scripts that's testing shared/static builds based on BUILD_SHARED_LIBS.

Use CMake built-in variable BUILD_SHARED_LIBS instead of custom TINYOBJLOADER_COMPILATION_SHARED

---

.gitmodules
pybind11/.gitmodules

Fixed gitmodules location according to https://git-scm.com/docs/gitmodules . This fixes Cmake's cloning error due to git failing to clone submodule.
Another way to fix this is to make pybind11 a git submodule so Cmake can recursively clone it.

Fixed gitmodules location

---

python/bindings.cc

The original indices member is not python friendly
```python
for shape in reader.GetShapes():
for idx in shape.mesh.indices:
vid.append(idx.vertex_index)
```
so I added a new method numpy_indices
```python
for shape in reader.GetShapes():
indices = shape.mesh.numpy_indices().reshape(-1, 3, 3)
vid.append(indices[..., 0])
nid.append(indices[..., 1])
tid.append(indices[..., 2])
print(np.concatenate(vid))
```

Add numpy_indices method

---

CMakeLists.txt

Set a target property WINDOWS_EXPORT_ALL_SYMBOLS to true every time shared libraries are built.
This enables the generation of symbols to be exported in Windows DLLs.

Fix for issue syoyo/tinyobjloader#217

---

README.md

Tinyobjloader is now live on [conan-center](https://bintray.com/conan/conan-center/tinyobjloader%3A_/_latestVersion).
This pull request documents the package as an installation option and adds the appropriate badge.
Fixes #206

Document conan package

---

tiny_obj_loader.h

Hi,I wanted to load a lot of smoothing groups, but tinyobjloader couldn't load 100 or more smoothing group ids.
So I fixed it.

correspond to 3 digit smoothing group index

---

CMakeLists.txt

Without this PR, when the downstream CMakeLists uses `find_package(tinyobjloader REQUIRED)`, there will be the below error:
```
CMake Error at modules/Mesh/CMakeLists.txt:68 (find_package):
By not providing "Findtinyobjloader.cmake" in CMAKE_MODULE_PATH this
project has asked CMake to find a package configuration file provided by
"tinyobjloader", but CMake did not find one.
Could not find a package configuration file provided by "tinyobjloader"
with any of the following names:
tinyobjloaderConfig.cmake
tinyobjloader-config.cmake
Add the installation prefix of "tinyobjloader" to CMAKE_PREFIX_PATH or set
"tinyobjloader_DIR" to a directory containing one of the above files.  If
"tinyobjloader" provides a separate development package or SDK, be sure it
has been installed.
```
The reason is …

fix cmake downstream find_package failure in double mode

---

python/bindings.cc

The `num_face_vertices` property is essential for interpreting `mesh_t.numpy_indices()`, and the `numpy_vertices()` function improves performance when pulling vertices.

Python bindings: Expose additional fields

---

tiny_obj_loader.h

It seems like the current version of the loader has a bug, because of which some objects may be skipped while loading an .obj file.
See the following .obj example:
```
mtllib test.mtl
v -1.000000 1.202466 1.000000
v 1.000000 1.202466 1.000000
v -1.000000 1.202466 -1.000000
v 1.000000 1.202466 -1.000000
vn 0.0000 1.0000 0.0000
v -1.000000 0.000000 1.000000
v 1.000000 0.000000 1.000000
v -1.000000 0.000000 -1.000000
v 1.000000 0.000000 -1.000000
vn 0.0000 1.0000 0.0000
usemtl None
o Plane.001
f 1//1 2//1 4//1
usemtl None1
o Plane
f 5//2 6//2 8//2
```
When the loader encounters the first object group, `o Plane.001`, it collects the face from the next line properly to the `prim_group` (line 2301). Then, the `usemtl` follows, and because the material is changed, the current `prim_group` is …

Fix: Some data may be ignored when loading objects from .obj

---

CMakeLists.txt
cmake_uninstall.cmake.in

This feature reduces the pain of having to remove the installed libraries and headers in `/usr/local/` one by one.
Before this change, after `sudo make install` there is no easy ways to remove these files, but with this change, we can simply type `sudo make uninstall` to remove these files.
This is inspired by [CMake FAQ](https://gitlab.kitware.com/cmake/community/wikis/FAQ#can-i-do-make-uninstall-with-cmake).

support sudo make uninstall for cmake

---

CMakeLists.txt

I realized I only fixed the problem of #229 for Linux while I was trying to update tinyobjloader for vcpkg. This fix allows double mode to work correctly in windows as well. I've tested it on vcpkg and it installs successfully with this change, and a minimal downstream example also works correctly.

fix cmake downstream find_package failure in double mode in windows

---

tiny_obj_loader.h

This pull request addresses the situation where a MTL file has a `map_Kd` and no `Kd`. In this situation the default diffuse value of 0,0,0 is used. The problem is that this results in a black material.
Other programs, such as blender, use a higher default diffuse value. I believe blender uses 0.6, which I also use here.

Set a decent diffuse value when map_Kd is present and Kd is not

---

tiny_obj_loader.h

My previous [pull request](https://github.com/syoyo/tinyobjloader/pull/249) resulted in compiler warnings on Windows.  The warnings were:
```
tiny_obj_loader.h
'=': truncation from 'double' to 'tinyobj::real_t'
```
This PR fixes those compiler warnings.

Fix windows compiler warnings

---

tiny_obj_loader.h

To avoid compiler warnings, for instance with
clang's -Werror=suggest-override .

operator(): Add override keywords

---

azure-pipelines.yml

Add support for Python 3.8.
I'm hoping this fixes the broken builds.

Bump cibuildwheel to 1.1.0

---

azure-pipelines.yml

The 10.13 image is being removed on 3/23.
https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

Bump MacOS image for Azure Pipelines

---

examples/viewer/README.md
models/mtl filename with whitespace issue46.mtl
models/mtl filename with whitespace issue46.obj
tests/tester.cc
tiny_obj_loader.h

As suggested on comment https://github.com/tinyobjloader/tinyobjloader/issues/46#issuecomment-728721876, this adds support for MTL files containing whitespaces, as long as the whitespaces are escaped with `\` inside an OBJ file.
I wasn't sure if it was ok to change the signature of the `SplitString` function. I could hardcode the escape character inside the function if that's preferred.
Added a test that demonstrates a combination of files with and without spaces.
I tried to keep the code style from the rest of the files, but please let me know if anything needs to be udpated.
I also added a couple of dependencies that weren't listed on the viewer example and that I needed to make it work.

Support MTL files with escaped whitespace

---

tiny_obj_loader.h

Hi!
Would it be possible to change int to size_t in SplitString?
This prevents a warning that currently occurs when tiny_obj_loader is compiled with -Wsign-compare.
Cheers!

Use size_t rather than int in SplitString.

---

CMakeLists.txt

Avoids a warning when cmake is too old (2.8.11 is from 2013, 3.2 is from 2015)

Bump required cmake version

---

tiny_obj_loader.h

This PR fixes the following clang warning report:
```
./tiny_obj_loader.h:2456:13: warning: implicit conversion increases floating-point precision: 'tinyobj::real_t' (aka 'float') to 'double' [-Wdouble-promotion]
if (j < 0.0) {
^ ~
```

Suppress clang warning: -Wdouble-promotion

---

tiny_obj_loader.h

There is no need to flush a stringstream.
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rio-endl

Remove library uses of std::endl on std::stringstream

---

tiny_obj_loader.h

To avoid annoying compilation error caused by MSVC's min/max define issue, use hard-coded int max value insted of `std::numeric_limits<int>::max().`

Hardcoded int max

---

tiny_obj_loader.h

The destructor serves no purpose and is a pessimization in case the `ObjReader` class is every returned or moved around, as it inhibits move-constructor generation in C++11 and above.

Remove unnecessary ObjReader destructor

---

tiny_obj_loader.h

Hi, thanks for this awesome tool to load obj files. I am using tinyobjloader for my tiny renderer, but I have met some problems on the "Living Room" scene from [McGuire Computer Graphics Archive](http://casual-effects.com/data/). Its obj file defines the same mtllib 181 times, and tinyobjloader will reload the file the same number of times! This mtllib file has 42 newmtl statements, so finally `reader.GetMaterials()` returns 7602 materials, causing my renderer OOM since it needs to load all texture maps of all materials.
This PR attempts to solve this issue by loading one mtl file only once. I record the filenames following "mtllib" in an `std::set<std::string>` so that the previously loaded mtl files will be skipped to avoid reloading. It should cover most scenarios in obj files. …

Fix mtllib reloading: load an mtl file only once

---

tiny_obj_loader.h

Hi! I've recently tried loading [this](https://github.com/jimmiebergmann/Sponza) model using this library, but the displacement maps have not been loaded because the model uses `map_Disp` instead of `disp` in the mtl file. Now `map_Disp` is not a standard statement according to [this](http://paulbourke.net/dataformats/mtl/) specification, but [assimp](https://github.com/assimp/assimp/blob/master/code/AssetLib/Obj/ObjFileMtlImporter.cpp), for example, accepts it as valid, so I felt that it is probably common  enough to be supported in this library as well.

Add alternative aliases for displacement maps during mtl parsing

---

tiny_obj_loader.h

Sorry for not properly testing my code before, but my previous commit introduces a warning when compiling with `Clang` and `-Wall`. This commit fixes that warning.

Fix a Clang warning

---

README.md
tiny_obj_loader.h

This pull request fixes the triangulation issue by implementing Newell's method to ensure polygons aren't flipped, as well as turns off triangulation for faces when `npolys == 3`. I have confirmed it fixes all flipped normals on multiple large datasets with many polygonal faces. This fixes issue #319 .

Fix normal flipping during triangulation 
