index.html
stylesheets/styles.css

Updated the doc page to reflect the Readme, added a little more information, and organized the page a little.

Cleaned up docs

---

tiny_obj_loader.h

Hello, I found three small mistakes while reading through the header file and fixed them.

Fix minor typos

---

catmark_torus_creases0.obj
test.cc
tiny_obj_loader.cc
tiny_obj_loader.h

+ optional parameter to triangulate polygons to maintain compatibility
+ added create tag test & example subd crease tag file from OpenSubD source code

subd support: n-sided polygons & pixar crease tags

---

tiny_obj_loader.h

I've replaced the calls to 'isdigit', 'isSpace' and 'isNewLine' functions with macros + some additional small performance tweaks.
The parse time of 'Power Plant' OBJ from http://graphics.cs.williams.edu/data/meshes.xml went down  from 30 seconds down to 26 seconds on Core i7 + SSD.

Performance tweaks

---

README.md

Fix a typo and add syntax highlighting language

---

examples/viewer/Makefile

Hi, rearranged the Makefile quite significantly, and added support for Mingw64. It could be better but its a start. It builds for me with TDMGCC-64.
Feedback is much welcome.

viewer: Added initial Makefile support for mingw64 (windows)

---

CMakeLists.txt

Someone may want to use this project as shared library.

Enable building as shared library

---

README.md

The readme code does not compile

missing size() in radme

---

tests/tester.cc
tiny_obj_loader.h

Make it easier to use an existing stream reader

---

tiny_obj_loader.h

Minor spelling fix

---

examples/viewer/stb_image.h
examples/viewer/viewer.cc

The previously used color based on the normal is combined with the diffuse color from the material definition.

Issue #74: Added basic diffuse texture support to examples/viewer

---

CMakeLists.txt

Fix some formatting inconsistencies, fix typo, update minimum CMake

---

python/main.cpp

Added material_indices dictionary to root Python object.

Added Python mapping from material ID to material name (#131)

---

tiny_obj_loader.h

I noticed a bug with badly selecting the axis. pnpoly required selecting an axis for running against its 2D algorithm. Doing what it suggested turned out to be a bad idea on some geometry, so I fixed it, and now here's a new PR.

ear clipping using pnpoly algorithm

---

examples/obj_sticher/obj_writer.cc

PR for open bounty test 2.

---

experimental/tinyobj_loader_opt.h

Material ids were not assigned to faces if the first face with this material was in another thread buffer than where usemtl command was.

Fix bug in not assigning material id to faces

---

examples/obj_sticher/obj_sticher.cc

Changes:
- Adapted the 1.0.x datastructure
- Switched <some_vector>.push_back() to precalculating sizes and just insertig, to increase performance.

Adapt 1.0.x format

---

tests/tester.cc
tiny_obj_loader.h

As discussed here https://github.com/syoyo/tinyobjloader/issues/177

Fixed #177

---

tiny_obj_loader.h

This PR introduces a new flag to optionally disable the loading of vertex colors:
* The default behavior of tinyOBJ (always providing vertex colors) remains unchanged
* Users can now disable the fallback to default vertex colors, meaning the array of vertex colors will be empty if no colors are given
* I added an additional flag to the `LoadOBJ` function. Don't know if this is the best way - foreseeing that there could be more flags, one could also introduce a struct for parameters instead. If one would summarize all two parameters in this one, however (the `triangulate` option and the new one), one would break compatibility with existing code
The reason why we need this is that we would like to know if there were vertex colors given or not. If there were some given, we would like to use …

Added option to disable default vertex colors

---

tiny_obj_loader.h

Fix Python build on Mac OS

---

azure-pipelines.yml

I ran into this while working on #256. This should make failures more obvious.

Move Python format check into separate CI job

---

tiny_obj_loader.h

Remove duplicate lookups

---

README.md

[![AUR version](https://img.shields.io/aur/version/tinyobjloader?logo=arch-linux)](https://aur.archlinux.org/packages/tinyobjloader)

Btw add aur badge

---

README.md

This PR will fix the issue: https://github.com/tinyobjloader/tinyobjloader/issues/300

Update example code in README.

---

CMakeLists.txt
fuzzer/README.md
fuzzer/fuzz_ParseFromString.cc

@syoyo would you agree to have the fuzz target in your upstream repository ?
cf https://github.com/google/oss-fuzz/pull/5488#discussion_r604597119

Fuzz target for oss-fuzz integration

---

azure-pipelines.yml
python/README.md

Since  python2.7 is not supported anymore

Bump windows vm image.

---

azure-pipelines.yml
examples/viewer/stb_image.h
examples/viewer/viewer.cc

Additional fix to PR 324 https://github.com/tinyobjloader/tinyobjloader/pull/324

Bc nine respect smoothing groups
